### ISSUE TITLE
pdt configure fails when gcc is gcc-#

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#109]
See https://travis-ci.org/zbeekman/taucmdr/builds/184140666 my WIP for expanding the build matrix.

To ensure that the GCC we want is ahead on the path, it gets linked into ~/bin which is prepended to the PATH. CC/CXX/FC get set to match the linked name without the full path. It is randomized whether the `gcc-#` name is created as the symbolic link and `CC` or if `gcc -> /usr/local/bin/gcc`.

When the suffixed version is used the pdt configure seems to fail. I think it should continue being able to build because some systems have GCC compilers suffixed with version numbers.

Hopefully someone else can confirm that this is in fact a bug. (I know I'm good at breaking things, but do I break them in the right way? :upside_down_face: )

**Comment by zbeekman** [comment]
pet --> pdt in title... thanks autocorrect...

**Comment by jlinford** [comment]
This is probably fixed in 2b9fac8c149cc2e3d757f2af153c1a434790ba9d.  Needs testing, but I'm closing for now.
