### ISSUE TITLE
Issues finding the compiler that the user is using/wants

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#110]
Caveat: I'm trying out what happens if `CC="ccache gcc-6"` before invoking/installing taucmdr.  Other issues persist with compilers with suffixes but no ccache: #109 

- Picking up /usr/bin/gcc: https://travis-ci.org/zbeekman/taucmdr/jobs/184164492#L1361
- But, user's ~/bin is at the front of PATH: https://travis-ci.org/zbeekman/taucmdr/jobs/184164492#L368
- And FC, CC, CXX etc. set to `ccache <compiler>-6` https://travis-ci.org/zbeekman/taucmdr/jobs/184164492#L480
- And symbolic links created in ~/bin : https://travis-ci.org/zbeekman/taucmdr/jobs/184164492#L482
- `$CC --version` `$FC --version` etc. all picking up correct GCC-6: https://travis-ci.org/zbeekman/taucmdr/jobs/184164492#L492
- MPICH doesn't seem to have an issue with ccache: https://travis-ci.org/zbeekman/taucmdr/jobs/184164493#L7960
- The build log exceeds the length so you can get the raw log at https://s3.amazonaws.com/archive.travis-ci.org/jobs/184164493/log.txt
- There you will see that:
   - taucmdr is picking up the compilers in `/usr/bin/gcc` rather than those ahead on the path in `~/bin/gcc-6` or that specified as `$CC` (`ccache gcc-6`): `Target.Host_CC : u'/usr/bin/gcc'`
   - taucmdr complains about not being able to identify the compiler wrapped by mpi: `Target.MPI_CC : u'/home/travis/usr/bin/mpicc'` *but* 

```
[31m[TAU] [0m[36mWARNING[0m
[31m[TAU] [0m
[31m[TAU] [0mUnable to identify compiler wrapped by wrapper 
[31m[TAU] [0m    '/home/travis/usr/bin/mpicc'. TAU will attempt to continue but may 
[31m[TAU] [0m    fail later on.
```

**Comment by jlinford** [comment]
This issue is very broad and a lot of points raised here have been fixed in the last year or so.  Can you please focus the question and provide a reproducer?  If not, please close the issue.  Thanks

**Comment by jlinford** [comment]
Also, curious if `ccache tau gcc-6` works.

**Comment by zbeekman** [comment]
yup this is definitely outdated... Let's close and I'll refocus as needed.
