### ISSUE TITLE
LD_LIBRARY_PATH conflicts with multiple Python environments

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#112]
From John W: 

> Ok, but did you notice that when I set the LD_LIBRARY_PATH the tau sampling calculation completed successfully? I think I need to be more careful about setting up my python environment and I'm trying out whether loading a python module on both riptide and spirit fixes the issue I was seeing.

**Comment by khsa1** [comment]
I cannot reproduce this error now. Loading PToolsRTE so that 2 Python environments are loaded does not cause any issues.
