### ISSUE TITLE
access to "tau" commands via setting path

### ISSUE THREAD

**Issue by srinathv** [ParaToolsInc/taucmdr#113]
Currrently if one puts <path to tau commander>/bin in your path you get the "tau" python program.
I'm wondering if there is a way to get more of TAU's commands like taudb_* and like, or is that a "tau trial ...." thing.

**Comment by jlinford** [comment]
Nope, the whole idea is there is only one command in TAU Commander so you don't have to know about all of TAU's various commands.  If you want TAU commands on your path just add TAU's bin directory to your path.
