### ISSUE TITLE
tau trial list error

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#127]
trial list returns an error if trial number is provided.

skhuvis@east02:~/workspace/taucmdr/examples/mm$ tau trial list
== Trial Configurations (/home/skhuvis/workspace/taucmdr/examples/mm/.tau/project.json) =============================================================================================================================================================================================

+--------+-----------+----------------------------+---------------------------------------------+
| Number | Data Size |          Command           |                In Directory                 |
+========+===========+============================+=============================================+
|   0    | 128.3KiB  | mpirun -np 4 ./matmult.exe | /home/skhuvis/workspace/taucmdr/examples/mm |
+--------+-----------+----------------------------+---------------------------------------------+

skhuvis@east02:~/workspace/taucmdr/examples/mm$ tau trial list 0
usage: tau trial list [trial_number] [trial_number] ... [arguments]
tau trial list: error: No trial with number='0'

**Comment by jlinford** [comment]
Fixed in f6d3b640fdded35b4161b56aa63f5242e34bd1ff
