### ISSUE TITLE
Need managed ompt build.

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#131]
CMake is now a TAU dependency:

[DEBUG taucmdr.util:426] which: no cmake in (/packages/intel/17/linux/bin/intel64:/home/jlinford/workspace/taucmdr/bin:/home/jlinford/workspace/taucmdr/pylint-1.6.5-py2.7.egg/EGG-INFO/scripts:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin)
[DEBUG taucmdr.util:426] ERROR: cmake version 2.8 or higher required to build OMPT support.
[DEBUG taucmdr.util:431] ['./configure', '-arch=x86_64', '-cc=icc', '-c++=icpc', '-fortran=intel', '-bfd=/home/jlinford/workspace/taucmdr/system/binutils/3c546bc41220ce7a8b8d3c22f1327d546d838dd9', '-unwind=/home/jlinford/workspace/taucmdr/system/libunwind/b5b365a800241ee3dee0cc4c8738598f763447bd', '-openmp', '-ompt=download', '-useropt=-O2#-g#-DTAU_MPI_F_STATUSES_IGNORE_ABSENT=1'] returned 1

And we can't rely on "-ompt=download" since network might not be available.

**Comment by khsa1** [comment]
Managed ompt build added in b35158513a890760d063b35073ecd8c4b661c019.
