### ISSUE TITLE
copper fail to install

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#148]
debug_log attached.
drmackay:copper01% module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.3
  2) eswrap/1.3.3-1.020200.1278.0
  3) java/jdk1.8.0_51
  4) craype-network-gemini
  5) craype-interlagos
  6) craype/2.2.1
  7) cray-mpich/7.1.0
  8) pbs/12.1.1.131502
  9) intel/14.0.2.144
 10) cray-libsci/13.0.1
 11) udreg/2.3.2-1.0502.10518.2.17.gem
 12) ugni/6.0-1.0502.10863.8.28.gem
 13) pmi/5.0.6-1.0000.10439.140.3.gem
 14) dmapp/7.0.1-1.0502.11080.8.74.gem
 15) gni-headers/4.0-1.0502.10859.7.8.gem
 16) xpmem/0.1-2.0502.64982.5.3.gem
 17) dvs/2.5_0.9.0-1.0502.2188.1.113.gem
 18) alps/5.2.4-2.0502.9774.31.12.gem
 19) rca/1.0.0-2.0502.60530.1.63.gem
 20) atp/1.7.5
 21) PrgEnv-intel/5.2.82
 22) cray-shmem/7.1.0

**Comment by drmackay** [comment]
[debug_log-copper-intel2.txt](https://github.com/ParaToolsInc/taucmdr/files/988957/debug_log-copper-intel2.txt)

**Comment by jlinford** [comment]
Looks like a TAU (not TAU Commander) bug, please try again with --tau=nightly to see if a recent TAU commit fixed this.

**Comment by drmackay** [comment]
OK - I entered the following sequence:
  43  11:42   cd taucmdr
    44  11:42   make clean
    45  11:43   ./configure --tau=nightly --prefix=$PET_HOME/pkgs/taucmdr-684c7101
    46  11:43   make install

I checked the debug_log file and the same error occurs at the same location:  
 "/opt/cray/mpt/7.1.0/gni/sma/include/shmem.h", line 241: error: identifier
[DEBUG taucmdr.util:454]           "__float128" is undefined
[DEBUG taucmdr.util:454]   extern void  shmem_float128_get(__float128 *trg, _CNST __float128 *src, 


I am attaching the debug_log file again.
[debug_log-coppernightly.txt](https://github.com/ParaToolsInc/taucmdr/files/990672/debug_log-coppernightly.txt)

**Comment by khsa1** [comment]
This issue is caused by tau commander setting the default host compiler family on copper to be Cray rather than Intel, even with PrgEnv-intel module loaded. On copper, the CC and CXX environment variables are set to cray compilers while on shepard they are set to intel compilers.

On shepard:
```
skhuvis@shepard06:~> module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.3                      7) cray-mpich/7.2.4                     13) totalview/8.13.0                     19) dmapp/7.0.1-1.0502.9501.5.219.ari    25) atp/1.8.3
  2) eswrap/1.3.3-1.020200.1278.0          8) pbs                                  14) intel/14.0.2.144                     20) gni-headers/3.0-1.0502.9684.5.2.ari  26) PrgEnv-intel/5.2.40
  3) switch/1.0-1.0502.54233.2.96.ari      9) bct-env/0.1                          15) cray-libsci/13.1.0                   21) xpmem/0.1-2.0502.55507.3.2.ari       27) cray-shmem/7.2.4
  4) craype-ivybridge                     10) ddn-env/0.1                          16) udreg/2.3.2-1.0502.9275.1.12.ari     22) dvs/2.5_0.9.0-1.0502.1873.1.145.ari
  5) craype-network-aries                 11) mpscp/1.3a                           17) ugni/5.0-1.0502.9685.4.24.ari        23) alps/5.2.1-2.0502.9041.11.6.ari
  6) craype/2.4.1                         12) totalview-support                    18) pmi/5.0.10-1.0000.11050.0.0.ari      24) rca/1.0.0-2.0502.53711.3.127.ari
skhuvis@shepard06:~> echo $CC
icc
```

On copper:

```
skhuvis@copper02:~> module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.3                       7) craype-interlagos                     13) pmi/5.0.6-1.0000.10439.140.3.gem      19) rca/1.0.0-2.0502.60530.1.63.gem
  2) eswrap/1.3.3-1.020200.1278.0           8) cray-mpich/7.1.0                      14) dmapp/7.0.1-1.0502.11080.8.74.gem     20) atp/1.7.5
  3) java/jdk1.8.0_51                       9) pbs/12.1.1.131502                     15) gni-headers/4.0-1.0502.10859.7.8.gem  21) PrgEnv-intel/5.2.82
  4) craype-network-gemini                 10) cray-libsci/13.0.1                    16) xpmem/0.1-2.0502.64982.5.3.gem        22) cray-shmem/7.1.0
  5) intel/14.0.2.144                      11) udreg/2.3.2-1.0502.10518.2.17.gem     17) dvs/2.5_0.9.0-1.0502.2188.1.113.gem
  6) craype/2.2.1                          12) ugni/6.0-1.0502.10863.8.28.gem        18) alps/5.2.4-2.0502.9774.31.12.gem
skhuvis@copper02:~> echo $CC
cc

```

**Comment by jlinford** [comment]
Confirmed, it compiles if I first set environment variables:
`
export CC=icc
export CXX=icpc
export F77=ifort
export F90=ifort
`

It should also work with cc, c++, ftn.  I'll look into it.

**Comment by jlinford** [comment]
Unwrap C++ compiler before passing to pdt_c++.

**Comment by khsa1** [comment]
33250a71cd9d4abc520a00283c6fa4973b386450 should fix this issue. Try the taucmdr-33250a71 installation on copper.

**Comment by drmackay** [comment]
Install works.
