### ISSUE TITLE
gordon fail to install

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#149]
debug_log attached
ordon01 drmackay/.tau% module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.3
  2) eswrap/1.3.3-1.020200.1278.0
  3) switch/1.0-1.0502.54233.2.96.ari
  4) craype-haswell
  5) craype-network-aries
  6) craype/2.4.1
  7) cray-mpich/7.2.4
  8) pbs
  9) bct-env/0.1
 10) mpscp/1.3a
 11) totalview/8.13.0
 12) intel/14.0.2.144
 13) cray-libsci/13.1.0
 14) udreg/2.3.2-1.0502.9275.1.12.ari
 15) ugni/5.0-1.0502.9685.4.24.ari
 16) pmi/5.0.10-1.0000.11050.0.0.ari
 17) dmapp/7.0.1-1.0502.9501.5.219.ari
 18) gni-headers/3.0-1.0502.9684.5.2.ari
 19) xpmem/0.1-2.0502.55507.3.2.ari
 20) dvs/2.5_0.9.0-1.0502.1873.1.145.ari
 21) alps/5.2.1-2.0502.9041.11.6.ari
 22) rca/1.0.0-2.0502.53711.3.127.ari
 23) atp/1.8.3
[debug_log-gordon-intel2.txt](https://github.com/ParaToolsInc/taucmdr/files/988964/debug_log-gordon-intel2.txt)

 24) PrgEnv-intel/5.2.40
 25) cray-shmem/7.2.4

**Comment by jlinford** [comment]
Looks like a TAU (not TAU Commander) bug, please try again with --tau=nightly to see if a recent TAU commit fixed this.

```
[DEBUG taucmdr.util:454] TauMetaDataMerge.cpp(80): error: "numRanks" has already been declared in the current scope
[DEBUG taucmdr.util:454]     int numRanks = __real_shmem_n_pes();
[DEBUG taucmdr.util:454]         ^
[DEBUG taucmdr.util:454] 
```

**Comment by jlinford** [comment]
Also, when pasting from the terminal please surround the text with three backticks to keep the text literal.  It's a lot easer to read that way.  E.g.

\`\`\`
paste from console
\`\`\`
