### ISSUE TITLE
fail to install on topaz

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#151]
debug log attached
[debug_log-topaz-intel2.txt](https://github.com/ParaToolsInc/taucmdr/files/988977/debug_log-topaz-intel2.txt)

Currently Loaded Modulefiles:
  1) java/1.8                3) mpi/sgimpt/2.13-11280
  2) compiler/intel/16.0.0   4) pbs/13.1.1.162303

**Comment by jlinford** [comment]
Will you please confirm that `oshcc` and `oshCC` invoke Intel compilers when `compiler/intel/16.0.0` is loaded?  Commander constructed the right configuration line:

```
cmd=['./configure', '-arch=x86_64', u'-cc=oshcc', u'-c++=oshCC', '-fortran=oshfort', '-bfd=/p/home/apps/unsupported/PETtools/CE/pkgs/taucmdr-684c7101/system/binutils/1b034b612ecdf12a3a1fe0cb3f569ec8cc1614ae', '-unwind=/p/home/apps/unsupported/PETtools/CE/pkgs/taucmdr-684c7101/system/libunwind/a6141aaf6c872dbc04868f2fb198cd59bcec52eb', '-shmem', '-pdt=/p/home/apps/unsupported/PETtools/CE/pkgs/taucmdr-684c7101/system/pdt/f44ed428acc01c7a8ef6eefecd89ac39ef737d61', '-pdt_c++=icpc', '-useropt=-O2#-g'], cwd='/p/home/apps/unsupported/PETtools/CE/pkgs/taucmdr-684c7101/system/tau/8a5a57e78fa0d19503a97c74444313a106d3e43a'
```

And TAU compilation succeeded:

```
[DEBUG taucmdr.cf.software.installation:322] tau installation at '/p/home/apps/unsupported/PETtools/CE/pkgs/taucmdr-684c7101/system/tau/8a5a57e78fa0d19503a97c74444313a106d3e43a' is valid
```

But TAU didn't add the `icpc` tag to the resulting TAU Makefile:

```
[DEBUG taucmdr.cf.software.tau_installation:775] Found makefiles: '['/p/home/apps/unsupported/PETtools/CE/pkgs/taucmdr-684c7101/system/tau/8a5a57e78fa0d19503a97c74444313a106d3e43a/x86_64/lib/Makefile.tau-shmem-pdt']'
[DEBUG taucmdr.cf.software.tau_installation:734] TAU tags: set(['pdt', 'shmem', 'icpc'])
[DEBUG taucmdr.cf.software.tau_installation:777] Searching for makefile with tags: set(['pdt', 'shmem', 'icpc'])
[DEBUG taucmdr.cf.software.tau_installation:756] Incompatible tags: set(['ompt', 'mpi', 'scorep', 'openmp', 'pgi', 'opari', 'gomp'])
[DEBUG taucmdr.cf.software.tau_installation:781] Will not use makefiles containing tags: set(['ompt', 'mpi', 'scorep', 'openmp', 'pgi', 'opari', 'gomp'])
[DEBUG taucmdr.cf.software.tau_installation:784] /p/home/apps/unsupported/PETtools/CE/pkgs/taucmdr-684c7101/system/tau/8a5a57e78fa0d19503a97c74444313a106d3e43a/x86_64/lib/Makefile.tau-shmem-pdt has tags: set(['pdt', 'shmem'])
[DEBUG taucmdr.cf.software.tau_installation:797] No TAU makefile exactly matches tags 'set(['pdt', 'shmem', 'icpc'])'
[DEBUG taucmdr.cf.software.tau_installation:803] No TAU makefile approximately matches tags 'set(['pdt', 'shmem', 'icpc'])'
```

Either TAU isn't identifying the Intel compiler, or the SHMEM compiler wrappers are invoking the wrong compiler.  Please check.

**Comment by jlinford** [comment]
I reproduced this on Thunder.  It's related to https://github.com/ParaToolsInc/taucmdr/blob/unstable/packages/taucmdr/cf/software/tau_installation.py#L565 where we override the unwrapped compilers with wrapped compilers when using OpenSHMEM.

We might not need to do that anymore.  Does anyone remember if this is fixed in TAU now? @khsa1

**Comment by khsa1** [comment]
No, this has not been fixed. `tau init --shmem` on grover with /usr/local/packages/openshmem-1.2, gives the following error when compiling a shmem code:
 /usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_notiopt'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `_gasneti_progressfn_enabled_gasneti_pf_barrier_BOOLEAN'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_nodes'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnetc_AMReplyMediumM'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_atomic32_native'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_wait_mode'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `elf_nextscn'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnete_barrier_pf'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_getNodeInfo'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_pshm'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_nosrclines'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_atomics_native'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_PAR'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnetc_hsl_lock'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_membars_native'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_mynode'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_atomic64_native'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `elf_strptr'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnet_init_GASNET_PARpshmFASTnodebugnotracenostatsnodebugmallocnosrclines'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnet_barrier_wait'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `elf_end'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_EXTENDED_SMP'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_noalign'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_CORE_SMP'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gelf_getclass'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `elf_begin'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnet_ErrorDesc'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_set_waitmode'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_getenv'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_getSegmentInfo'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `elf_getshstrndx'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_notrace'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_nodebugmalloc'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_64bit'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `elf_kind'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `_gasneti_progressfn_enabled_gasneti_pf_vis_COUNTED'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnetc_AMRequestMediumM'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_MaxLocalSegmentSize'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnetc_AMPoll'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_vis_progressfn'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_nodebug'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnet_barrier_notify'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_timers_native'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `elf_version'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_nodeinfo'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gelf_getehdr'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_nostats'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasneti_linkconfig_idiotcheck_FAST'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `elf_getdata'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnetc_hsl_unlock'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnet_ErrorName'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gasnetc_attach'
/usr/local/packages/openshmem-1.2/lib/libopenshmem.so: undefined reference to `gelf_getshdr'
Error: Command(Executable) is -- /opt/intel/17/linux/bin/intel64/icc
Error: Full Command attempted is -- /opt/intel/17/linux/bin/intel64/icc    simple.o  @/storage/users/skhuvis/workspace/taucmdr/system/tau/f3c91a3664097d2a080ef67a41db6dbbc287de7c/x86_64/lib/wrappers/shmem/link_options.tau    -L/storage/users/skhuvis/workspace/taucmdr/system/tau/f3c91a3664097d2a080ef67a41db6dbbc287de7c/x86_64/lib -ltau-icpc-shmem-pdt              -lbfd       -Wl,--export-dynamic  -lrt            -ldl -lm  -L/storage/packages/gcc/4.9.3/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.9.3/ -L/usr/local/packages/gcc/4.9/bin/../lib64 -lstdc++ -lgcc_s   -L/storage/users/skhuvis/workspace/taucmdr/system/tau/f3c91a3664097d2a080ef67a41db6dbbc287de7c/x86_64/lib -lTauShmem-icpc-shmem-pdt -L/usr/local/packages/openshmem-1.2/lib -lopenshmem  -L/storage/users/skhuvis/workspace/taucmdr/system/tau/f3c91a3664097d2a080ef67a41db6dbbc287de7c/x86_64/lib/static-icpc-shmem-pdt      @/storage/users/skhuvis/workspace/taucmdr/system/tau/f3c91a3664097d2a080ef67a41db6dbbc287de7c/x86_64/lib/wrappers/shmem/link_options.tau -o simple

**Comment by jlinford** [comment]
@khsa1 can you please move that last comment to a new issue about gasnet headers/libs on grover?  Let's keep this thread about topaz, thanks!

**Comment by drmackay** [comment]
working fine with C code.
