### ISSUE TITLE
fail to install on shepard

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#152]
debug_log attached
[debug_log-shepard-intel2.txt](https://github.com/ParaToolsInc/taucmdr/files/988985/debug_log-shepard-intel2.txt)

shepard02 drmackay/.tau% module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.3
  2) eswrap/1.3.3-1.020200.1278.0
  3) switch/1.0-1.0502.54233.2.96.ari
  4) craype-network-aries
  5) craype-ivybridge
  6) craype/2.4.1
  7) cray-mpich/7.2.4
  8) pbs
  9) bct-env/0.1
 10) ddn-env/0.1
 11) mpscp/1.3a
 12) totalview-support
 13) totalview/8.13.0
 14) intel/14.0.2.144
 15) cray-libsci/13.1.0
 16) udreg/2.3.2-1.0502.9275.1.12.ari
 17) ugni/5.0-1.0502.9685.4.24.ari
 18) pmi/5.0.10-1.0000.11050.0.0.ari
 19) dmapp/7.0.1-1.0502.9501.5.219.ari
 20) gni-headers/3.0-1.0502.9684.5.2.ari
 21) xpmem/0.1-2.0502.55507.3.2.ari
 22) dvs/2.5_0.9.0-1.0502.1873.1.145.ari
 23) alps/5.2.1-2.0502.9041.11.6.ari
 24) rca/1.0.0-2.0502.53711.3.127.ari
 25) atp/1.8.3
 26) PrgEnv-intel/5.2.40
 27) cray-shmem/7.2.4

**Comment by jlinford** [comment]
This also appears to be a TAU (not commander) bug:

```
[DEBUG taucmdr.util:454] TauMetaDataMerge.cpp(80): error: "numRanks" has already been declared in the current scope
[DEBUG taucmdr.util:454]     int numRanks = __real_shmem_n_pes();
[DEBUG taucmdr.util:454]         ^
```

Please try with `--tau=nightly`.
