### ISSUE TITLE
thunder successfully install taucmdr - but tau fails during runtime

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#155]
This may be a tau problem?  Not sure.
-David
[debug_log-thunder-failat-rt.txt](https://github.com/ParaToolsInc/taucmdr/files/991902/debug_log-thunder-failat-rt.txt)

**Comment by jlinford** [comment]
Pretty sure b9f963303b754b95da1cc42b8e4163502046b3e1 fixed this, please try again with the latest commit

**Comment by drmackay** [comment]
Resolved - thunder runs ISx now.
