### ISSUE TITLE
tau show exposes tag error on shepard

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#157]
[debug_log.txt](https://github.com/ParaToolsInc/taucmdr/files/997419/debug_log.txt)

occurs when entering "tau show 1"

**Comment by jlinford** [comment]
Ugh, this is also a bug in TAU.  TAU Commander configures TAU for GNU:
```
Creating subprocess: cmd=['./configure', '-arch=craycnl', '-cc=gcc', '-c++=g++', '-useropt=-O2#-g'],
```
but then TAU ignores the command line flags and decides to use Intel compilers:
```
[DEBUG taucmdr.util:464] Default C++ compiler will be CC
[DEBUG taucmdr.util:464] Setting F90 compiler based on requested: intel
[DEBUG taucmdr.util:464] Default Fortran compiler will be Intel ifort
[DEBUG taucmdr.util:464] Default C compiler will be cc
```

**Comment by jlinford** [comment]
Please try with 0848622e8d58e6ca5ed0a1907fba63f967e61e9c.

**Comment by jlinford** [comment]
@drmackay , please try again, it should work now.
