### ISSUE TITLE
problems exporting on armstrong

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#159]
taucmdr installs.  It appears to collect data as well.  Preparing to view data fails.   I tried 
tau show 0 --profile-tool pprof > zer.txt 
this failed.  So I tried to export the data with : 
 tau trial 1 export
This gave me errors as well.  So I have not verified the collected data on armstrong.
[debug_log-armstrong.txt](https://github.com/ParaToolsInc/taucmdr/files/998019/debug_log-armstrong.txt)

**Comment by jlinford** [comment]
Please try with 0848622e8d58e6ca5ed0a1907fba63f967e61e9c.

**Comment by drmackay** [comment]
I pulled 0848622 from unstable branch on armstrong.  Both --profile-tool pprof and tau trial export function with this build - so I am closing this issue.
