### ISSUE TITLE
tau show consistently fails

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#160]
I re installed this just to make sure - but I get same experience on Gordon everytime.
tau trial export
results in:
CRITICAL
[TAU]
[TAU] TAU Makefile not found for tags '' in '/p/home/app/PET/pkgs/taucmdr-5f623965/system/tau/2aee5bbfdb5f12b7300502f118641b13a0d70d33'
[TAU] 

tau show --profile-tool pprof
results in

[TAU] CRITICAL
[TAU]
[TAU] TAU Makefile not found for tags '' in '/p/home/app/PET/pkgs/taucmdr-5f623965/system/tau/2aee5bbfdb5f12b7300502f118641b13a0d70d33'
[TAU]
[debug_log-gordon.txt](https://github.com/ParaToolsInc/taucmdr/files/1005956/debug_log-gordon.txt)

**Comment by jlinford** [comment]
This was fixed in 0848622e8d58e6ca5ed0a1907fba63f967e61e9c.  Try the latest commit on unstable, thanks,
