### ISSUE TITLE
new unstable branch doesn't build on gordon

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#161]
show and export failed with master branch on gordon.  I installed the new branch from unstable - now taucommander does not complete install.
1030  6:53    git clone https://github.com/ParaToolsInc/taucmdr.git
  1031  6:53    git checkout unstable
  1032  6:53    cd taucmdr
  1033  6:53    git checkout unstable
  1034  6:53    git pull
  1035  6:53    curl http://fs.paratools.com/tau-nightly.tgz > packages/tau.tgz
  1036  6:53    git log
  1037  6:54    history | grep config
  1038  6:54    ./configure --prefix==$PET_HOME/pkgs/taucmdr-33250a71
  1039  6:54    make install
[debug_log_gordon_unstable.txt](https://github.com/ParaToolsInc/taucmdr/files/1006955/debug_log_gordon_unstable.txt)

**Comment by khsa1** [comment]
You have an extra '=' in the configure command. Try:
make clean
rm -r $PET_HOME/pkgs/taucmdr-33250a71
./configure --prefix=$PET_HOME/pkgs/taucmdr-33250a71

**Comment by jlinford** [comment]
@drmackay, you installed it in a directory named "=", see your debug log.  That should be an acceptable path so this is a bug.

**Comment by jlinford** [comment]
To clarify, `/p/home/drmackay/taucmdr/=/app/PET/pkgs/taucmdr-33250a71/` is a valid path so this is a bug, though I don't know why anyone would intentionally install in a directory named "=".

**Comment by jlinford** [comment]
This is fixed in 72ac11e2a602db0b6e061f5db454a79190d41c94, i.e. you can now install to a directory named "=" in the taucmdr source folder (although why you'd ever do that is beyond me).  I even threw in a warning message in case the prefix starts with "=" to hopefully prevent this from happening again.

**Comment by jlinford** [comment]
@drmackay Will you please close this issue when you confirm it works on Grover with the right `--prefix` flag?  No need to test `--prefix==`. I've tested that on east03.

**Comment by drmackay** [comment]
Tested install on gordon - it is working there.  I will test it on grover too.
