### ISSUE TITLE
fortran trace fails to export (excalibur)

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#162]
export of ISx (C) traces works fine.  Attempts to export fortran traces (npb) sometimes results in errors (sometimes export works):
errors are like this:
. . . 
144 excalibur07> tau trial export 2
[TAU] Merging 128 TAU trace files...
[TAU] Completed in 5.740867 seconds
[TAU] Converting TAU trace files to SLOG2 format...
[TAU] Completed in 1.006014 seconds
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU]
[TAU] CRITICAL
[TAU]
[TAU] An unexpected InternalError exception was raised:
[TAU]
[TAU] Nonzero return code from tau2slog2
[TAU]
[TAU] Traceback (most recent call last):
[TAU]   File "/usr/cta/pet/pkgs/taucmdr-33250a71/bin/tau", line 70, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/p/app/pet/pkgs/taucmdr-33250a71/bin/../packages/taucmdr/cli/commands/__main__.py", line 133, in
. . . 
[debug_log-excalibur-trace.txt](https://github.com/ParaToolsInc/taucmdr/files/1008963/debug_log-excalibur-trace.txt)

**Comment by drmackay** [comment]
The export of slog2 files is common.  I have reproduced this on gordon as well as excalibur.    It is inconsistent though - like a race condition.  I will enter "tau trial export 2" and it will fail as above, then I will immediately enter the same command and it will complete apparently successful.  I would say it reproduces about 12% of the time - it is not everytime but it is not uncommon either (like a race condition).

**Comment by jlinford** [comment]
Good data!  It sounds like a problem in TAU's underlying tau2slog2 command.  Can you show debug logs from a failure and from a success?

**Comment by drmackay** [comment]
I am attaching a log file from Gordon.   One is the full log file- the other is a segment of that full log file - in this section I believe I enter tau trial export 6 and enter this 3 times.  The first couple of times fail and then on the third try a slog2 file is written - I am not convinced that the slog2 file written though is a valid slog2 file (containing correct data).
[debug_log-gord.txt](https://github.com/ParaToolsInc/taucmdr/files/1012778/debug_log-gord.txt)

[debug-seg.txt](https://github.com/ParaToolsInc/taucmdr/files/1012777/debug-seg.txt)
