### ISSUE TITLE
Usage with Autotools and similar projects

### ISSUE THREAD

**Issue by ohearnk** [ParaToolsInc/taucmdr#176]
The philosophy of "just prefix all commands with tau" and let shell environment magic happen behind the scenes does not work with Autotools or similar projects if you want to perform static linkage for instrumented profiling/tracing.  That is, running

`./configure CC="tau $CC"`

does not work with recent versions of Autotools (e.g., Autoconf v2.69, Automake v1.15, libtool v2.4.6).

Direct usage of the wrappers provided by TAU was a convenient way around this issue (e.g., tau_cc.sh).  These scripts are installed under ${TAUCMDR_INSTALL_DIR}/system/tau/tau-${TAU_VERSION}/tools/src.

Are these wrapper scripts exposed anywhere in TAU commander?

**Comment by jlinford** [comment]
Have to use CC="tau -q $CC" to suppress output from `tau`.  There's a related verbosity issue somewhere...
