### ISSUE TITLE
Unable to copy project

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#178]
Enter commands:
                    tau project copy mm mmdup --application mm --measurements profile --targets drmackay-VirtualBox

Error comes back:
          /examples/mm$ tau project copy mm mmdup --application mm --measurements profile --targets drmackay-VirtualBox
     {'applications': ['mm'], 'measurements': ['profile'], 'name': 'mmdup', 'targets': ['drmackay-VirtualBox']}
[TAU] 
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
   [TAU] 
   [TAU] CRITICAL
   [TAU] 
   [TAU] An unexpected ModelError exception was raised:
   [TAU] 
   [TAU] Project: Invalid non-integer ID 'profile' in 'measurements'
   [TAU] 
  [TAU] Traceback (most recent call last):
  [TAU]   File "/home/drmackay/taucmdr/scripts/tau", line 70, in <module> 
  [TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/cli/commands/__main__.py", 
  [TAU]     line 133, in main
  [TAU]     return cli.execute_command([cmd], cmd_args)
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/cli/__init__.py", line 292, in
  [TAU]      execute_command
  [TAU]     return main(cmd_args or [])
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/cli/cli_view.py", line 87, in 
  [TAU]     main
  [TAU]     return cli.execute_command([args.subcommand], args.options, self.module_name)
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/cli/__init__.py", line 292, in
  [TAU]      execute_command
  [TAU]     return main(cmd_args or [])
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/cli/commands/project/copy.py",
  [TAU]      line 102, in main
  [TAU]     return self._copy_record(PROJECT_STORAGE, data, key)
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/cli/cli_view.py", line 538, in
  [TAU]      _copy_record
  [TAU]     return self._create_record(store, data)
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/cli/cli_view.py", line 124, in
  [TAU]      _create_record
  [TAU]     ctrl.create(data)
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/model/project.py", line 100, 
  [TAU]     in create
  [TAU]     return super(ProjectController, self).create(data)
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/mvc/controller.py", line 191, 
  [TAU]     in create
  [TAU]     data = self.model.validate(data)
  [TAU]   File "/home/drmackay/taucmdr/scripts/../packages/taucmdr/mvc/model.py", line 277, in 
  [TAU]     validate
  [TAU]     raise ModelError(cls, "Invalid non-integer ID '%s' in '%s'" % (eid, attr))
  [TAU] ModelError
  [TAU] 
  [TAU] 
  [TAU] This is a bug in TAU Commander.
  [TAU] Please send '/home/drmackay/.tau/debug_log' to <support@paratools.com> for assistance.
  [TAU] 
  [TAU]
[debug_log.txt](https://github.com/ParaToolsInc/taucmdr/files/1265334/debug_log.txt)
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by khsa1** [comment]
89b1cb69c9eea62 should resolve this issue. Can you pull the latest version of unstable and check if it is working now?

**Comment by jlinford** [comment]
Tests pass!
