### ISSUE TITLE
"tau help all" fails

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#179]
"tau help --help" lists options as <command>|<file>|all
Entering "tau help all" generates the error shown below:
tau help all
   [TAU] 
   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  [TAU] 
 [TAU] CRITICAL
 [TAU] 
 [TAU] An unexpected TypeError exception was raised:
 [TAU] 
 [TAU] 'module' object has no attribute '__getitem__'
 [TAU] 
 [TAU] Traceback (most recent call last):
 [TAU]   File "/home/drmackay/tau4all/bin/tau", line 70, in <module>
 [TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
 [TAU]   File 
 [TAU]     "/home/drmackay/tau4all/bin/../packages/taucmdr/cli/commands/__main__.py",
 [TAU]      line 132, in main
 [TAU]     return cli.execute_command([cmd], cmd_args)
 [TAU]   File "/home/drmackay/tau4all/bin/../packages/taucmdr/cli/__init__.py", 
 [TAU]     line 292, in execute_command
 [TAU]     return main(cmd_args or [])
 [TAU]   File 
 [TAU]     "/home/drmackay/tau4all/bin/../packages/taucmdr/cli/commands/help.py",
 [TAU]      line 139, in main
 [TAU]     return self.exit_with_fullhelp()
 [TAU]   File 
 [TAU]     "/home/drmackay/tau4all/bin/../packages/taucmdr/cli/commands/help.py",
 [TAU]      line 112, in exit_with_fullhelp
 [TAU]     commands = cli.get_all_commands()
 [TAU]   File "/home/drmackay/tau4all/bin/../packages/taucmdr/cli/__init__.py", 
 [TAU]     line 210, in get_all_commands
 [TAU]     all_commands.append(mod['__module__'].__name__)
 [TAU] TypeError: 'module' object has no attribute '__getitem__'
 [TAU] 
 [TAU] This is a bug in TAU Commander.
 [TAU] Please send '/home/drmackay/.tau/debug_log' to <support@paratools.com> for
 [TAU]      assistance.
 [TAU]

[debug_log-text.txt](https://github.com/ParaToolsInc/taucmdr/files/1271116/debug_log-text.txt)

**Comment by khsa1** [comment]
Fixed in 9b99813335613a8.
