### ISSUE TITLE
Don't let user `tau init` in $HOME

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#184]

**Comment by zbeekman** [comment]
This causes dangerous breakage. Work around is to `rm -rf ~/.tau && mkdir ~/.tau && touch user.json`

**Comment by khsa1** [comment]
Fixed in d7fcdea233c6c900c3.

**Comment by zbeekman** [comment]
Thanks Sam! Nice work protecting people who have a penchant for breaking things (like me!) from themselves. 🎉
