### ISSUE TITLE
`tau init --mpi-compilers Intel` on Cray may confuse users

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#205]
Feel free to mark this as "won't fix" but on Onyx, `tau init --mpi-compilers Intel` after `module swap PrgEnv-cray PrgEnv-intel` complains about missing Intel compilers. I found this mildly confusing. Despite this, it seems that taucmdr is correctly wrapping the intel MPI compilers, which are wrapped by Cray's `ftn`

**Comment by jlinford** [comment]
Message now reads:
```
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] Intel Compilers supporting the Message Passing Interface (MPI) not found.
[TAU] 
[TAU] Hint: Check that these commands are in your PATH: mpiicc, mpiicpc, mpiifort
[TAU] 
[TAU] TAU cannot proceed with the given inputs.
[TAU] Please check the configuration for errors or contact <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

Hopefully that's a little more clear.  It's the Intel MPI compilers that are missing, not regular Intel compilers.  `tau init` should be sufficient on cray because `os.environ['PE_ENV']` tells us which PrgEnv module is loaded.
