### ISSUE TITLE
Specify OpenMP measurement library on `tau init`

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#209]
Sameer would like to be able to use syntax like `tau init --openmp=ompt` instead of the two commands `tau init --openmp && tau meas ed sample --openmp=ompt`

**Comment by jlinford** [comment]
Actually this is harder than it sounds.  I'm going to steal this issue :-D

**Comment by zbeekman** [comment]
👍

**Comment by jlinford** [comment]
Appears to be working as of c2d698dd9f6ca6ef9661fce443b405d9f01a25bd.  This was a lot harder than it should have been, mainly because I wasn't particularly bright when I implemented commands calling other commands.  All that's fixed now!
