### ISSUE TITLE
openmp display of example matmult_omp

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#216]
Using example ./examples/matmult_omp.  If I run a simple build (make), the default is sample with openmp ignore.  I run this tau mpirun -np 4 ./matmult and I get 4 profile files, I run tau show and I see the 4 mpi ranks as well as the threads for each openmp thread in paraprof.  Now if I activate openmp in sampling the openmp threads disappear.  Commands:
     tau meas copy sample sample-omp
     tau meas edit sample-omp --openmp ompt
     tau select sample-omp
     make clean
    make
    tau mpirun -np 4 ./matmult
    tau show
Now when I run tau show with openmp expected to be recorded -instead openmp disappears!    The paraprof view shows only the four mpi ranks, no threads for the openmp threads.    So if tau settings are to ignore openmp I get openmp information, if tau settings are to capture openmp I don't get openmp data.   This should be fixed.

**Comment by jlinford** [comment]
Hi David,
Can you please clarify?

This doesn't make sense:
> ... sample with openmp ignore ...
> I run this tau mpirun -np 4 ./matmult and I get 4 profile files
> ... I see the 4 mpi ranks as well as the threads for each openmp thread in paraprof.

If you have four profile files then there can't possibly be profiles for each OpenMP thread.  You'd need to have 4 * OMP_NUM_THREADS profiles.

Is it possible you're confusing the profiles with --openmp=ignore and --openmp=ompt?

**Comment by jlinford** [comment]
OK, I see the problem.  Yes, with `--openmp=ignore` I see 16 profile files (4*OMP_NUM_THREADS), but with `--openmp=ompt` I see only 4 profile files, one for each MPI rank.

On east03.paratools.com:
```
cd examples/matmult_omp
tau init --mpi --openmp

make clean
make

export OMP_NUM_THREADS=4
export MV2_ENABLE_AFFINITY=0
tau mpirun -np 4 ./matmult
# Trial 0 produced 16 profile files.
tau show
# I see four MPI ranks, each with four OpenMP threads

tau meas copy sample sample-omp
tau meas edit sample-omp --openmp ompt
tau select sample-omp

make clean
make
tau mpirun -np 4 ./matmult
# Trial 0 produced 4 profile files.
# Hmm.... not good
```

**Comment by jlinford** [comment]
@drmackay OK, it should be fixed now, please try again.  Thanks!
