### ISSUE TITLE
unable to profile simple application

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#217]
I created a variant of the mpi pi program to run serially to demonstrate effects of throttling.
This works with compiler instrumentation but fails to build with profile measurement (source instrumentation)

I used:
   tau init
   tau select profile
   tau g++ -g -O2 serialPi.cpp
At this point compilation fails iwth:
   In file included from /home/drmackay/tau4all/system/tau/tau-2.26.3/include/Profile/Profiler.h:86:0,
                 from serialPi.inst.cpp:1:
   /home/drmackay/tau4all/system/tau/tau-2.26.3/include/TAU.h:23:0: warning: "TAU_ENABLED" redefined
    #define TAU_ENABLED
    ^
   <command-line>:0:0: note: this is the location of the previous definition

This example works fine with compiler instrumentation.
The file serialPi.cpp is copied below:

#include <iostream>
#include <stdlib.h>

#include <math.h>
#include <climits>

// This example is adapted from "Using MPI, second edition" 
// by Gropp, Lusk, and Skellum

int computeRandom()
{
    return random();
}

double runWorker()
{
    const int numRands = 1000;
    int* rands = new int[ numRands ];

    double x;
    double y;
    bool notDone = true;
    int in = 0; 
    int out = 0;
    double epsilon = 0.00000001;
    double error;
    double Pi;

    while ( notDone )
    {
       for ( int i = 0; i < numRands; )
       {
           rands[i] = computeRandom();
           if ( rands[i] <= INT_MAX ) ++i;
       }

        for ( int i = 0; i < numRands; )
        {
            x = (((double)(rands[i++]))/(double)(INT_MAX)) * 2 - 1;
            y = (((double)(rands[i++]))/(double)(INT_MAX)) * 2 - 1;
            if (( x*x + y*y ) < 1.0 ) ++in;
            else ++out;
        }

        Pi = (4.0 * in) / ( in + out );
        error = fabs( Pi - 3.141592653589793238462643 );
        notDone = ( (error > epsilon) && (in + out) < 10000000 );
    }

    delete[] rands;
    return Pi;
 }

int main( int argc, char* argv[] )
{
    double pi;
    pi = runWorker( );

        std::cout << "Pi is " << pi << std::endl;

}

**Comment by jlinford** [comment]
That's a compiler warning, not an error.  It's working fine for me on east03 when I try the same commands.
