### ISSUE TITLE
Incorrect file permissions detected

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#231]
TAU Commander uses os.access to check if it has write permissions inside of a directory. I believe os.access uses the POSIX permissions to check if the user has access to a file. However, this has caused a few problems on Owens.

I have write access to the installation directory but it is only write-mounted on a specific node. This means that if I run taucmdr from any other node it believes I still have write access and will fail.
Additionally, Owens uses NFSv4 Filesystem ACLs on certain directories so it's possible for the POSIX ACL to show that a user has permission for a directory when in reality they do not.

Could taucmdr use a different method to determine write access or allow the user to pass an option telling it not to attempt to write to the system directory?

**Comment by jlinford** [comment]
Hi Sam!  It should be easy to fix, I think we already do something similar for discovering if /dev/shm supports executables.  Do you have a helpful debug log?

**Comment by khsa1** [comment]
I'm not sure how helpful it will be but here is a debug log. It tries to write .lock to the system directory and fails since I do not have access to it.


[debug_log.txt](https://github.com/ParaToolsInc/taucmdr/files/1442614/debug_log.txt)
