### ISSUE TITLE
Allow multiple arguments for commands where it makes sense

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#248]
I often launch a sequence of jobs with dependencies using `qsub ... -W depend=afterany:${JID} ...` and if the first job fails it's likely that I got the config/setup wrong and the subsequent jobs also fail. Pruning these trials from taucmdr is a pain because

```
tau trial del 7 8 9 10
```

Is not a valid command. There may be other commands where it would make sense to allow multiple arguments to be passed. Ever `delete` command should be able to handle multiple arguments. There may be other commands where a user wants to operate on multiple items at once, but without more coffee I'm having trouble thinking of them at the moment.

**Comment by khsa1** [comment]
I have allowed for multiple arguments into all the `tau delete` subcommands in 78ce607468651bb46c1c82cd59a9306e9d56b3ba and 953ccfab20129213dcbf4e0965e90642881e57b5. I've gone through the other commands but do not see any others that do not allow multiple arguments when they should.
