### ISSUE TITLE
Allow out of tree trials

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#252]
Inspired by git's `-C` and `--git-dir=<path>` flags.

This would allow the .tau project to be kept with the project source and then experiments could be run from a `$WORKDIR` (or vice versa).

Example usage:

```
tau --tau-dir ~/code/app1/.tau aprun -B app1.x
```

**Comment by khsa1** [comment]
Added in c0394229159750775ceb374da38848e35da803ee.
