### ISSUE TITLE
--tau nightly doesn't do anything other than download and build nightly tau

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#254]
If tau-2.27 is still installed then --tau nightly doesn't actually seem to use the tau nightly tau installation; tau-=2.27 is still used when compiling and running the application with TAU Commander.

**Comment by zbeekman** [comment]
Also, the `tau_source` target property is set to nightly, but 2.27 still gets used if it's installed.

**Comment by khsa1** [comment]
I am having trouble reproducing this issue. What system are you running on? Could you also include a debug log or list of commands to reproduce the bug?

**Comment by zbeekman** [comment]
I installed tau stable first, then tried nightly... but this may be a red
herring... It's possible that the issue is that the nightly tarbal is not
actually nightly. What URL does commander  pull nightly from? (and I'd hold
off looking at this for a little bit, until I can get you more info and see
if this is actually the source of the problem.

**Comment by zbeekman** [comment]
OK, seems like I was reading the logs wrong. Closing.
