### ISSUE TITLE
Create a MAX_THREADS optional attribute for applications

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#256]
It is hard to divine an appropriate setting for -DTAU_MAX_THREADS simply from the requested architecture. If this is overestimated, TAU may very likely run out of memory during finalization of sampling.

Creating a max-threads or similarly named application attribute to help ensure that TAU is configured correctly could take the guess work out of this.

**Comment by zbeekman** [comment]
This may need to be a target attribute rather than an application attribute. Still investigating.

**Comment by khsa1** [comment]
Added in f08854739a12c9a5d0e1f0634e4cf1b76cc4d80e.
