### ISSUE TITLE
TAU init on Topaz

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#257]
When I do the following, `tau init` fails on topaz:

```
module unload compiler/intel mpi
module load compiler/intel/15.0.3 mpi/sgimpt/2.12-11218
module load create
```

I tried `tau init`, `tau init --mpi T`, `tau init --mpi T --shmem F` and all fail with: 

```
> tau init
[TAU] System MPI C compiler '/p/home/apps/sgi/mpt-2.12-sgi712r26/bin/mpicc' wraps '/p/home/apps/intel/parallel_studio_2015_u3/composer_xe_2015.3.187/bin/intel64/icc'
[TAU] System MPI C++ compiler '/p/home/apps/sgi/mpt-2.12-sgi712r26/bin/mpicxx' wraps
[TAU]     '/p/home/apps/intel/parallel_studio_2015_u3/composer_xe_2015.3.187/bin/intel64/icpc'
[TAU] System MPI Fortran compiler '/p/home/apps/sgi/mpt-2.12-sgi712r26/bin/mpif90' wraps
[TAU]     '/p/home/apps/intel/parallel_studio_2015_u3/composer_xe_2015.3.187/bin/intel64/ifort'
[TAU] Created a new project named 'longline'.
[TAU] Added application 'longline' to project configuration 'longline'.
[TAU] ****************************************************************************************************************************************************************
[TAU]
[TAU] WARNING
[TAU]
[TAU] Assuming '/p/home/apps/sgi/mpt-2.12-sgi712r26/bin/oshCC' is a OpenSHMEM compiler but it could be to any of these: OpenSHMEM, SOS
[TAU] If this assumption is incorrect then you should manually specify your compilers
[TAU]
[TAU] ****************************************************************************************************************************************************************
[TAU] ****************************************************************************************************************************************************************
[TAU]
[TAU] WARNING
[TAU]
[TAU] Assuming '/p/home/apps/sgi/mpt-2.12-sgi712r26/bin/oshcc' is a SOS compiler but it could be to any of these: SOS, OpenSHMEM
[TAU] If this assumption is incorrect then you should manually specify your compilers
[TAU]
[TAU] ****************************************************************************************************************************************************************
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU]
[TAU] CRITICAL
[TAU]
[TAU] '/p/home/apps/sgi/mpt-2.12-sgi712r26/bin/oshcc' isn't actually a SOS SHMEM C compiler since it doesn't accept arguments ['-show'].
[TAU]
[TAU] Hint: Try `tau --help`
[TAU]
[TAU] TAU cannot proceed with the given inputs.
[TAU] Please check the configuration for errors or contact <support@paratools.com> for assistance.
[TAU]
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

This is from my ~/longline directory. If I go to ~/Sandbox/taucmdr and try it there it works without a problem. What gives?

**Comment by zbeekman** [comment]
OK, more digging and this appears to happen *only* when `tau init` is run in a directory whose parent directory is the home directory. @khsa1 if you have a chance to look into this, I would appreciate it, I've got a lot of other things to attend to right now.

**Comment by khsa1** [comment]
Are you sure this error only happens when the parent directory is HOME? I am getting this error message in any case. It also doesn't really make sense to me that directory location would affect an issue with SHMEM compilers, but I guess it's possible.

I am looking into the SHMEM issue. Specifying `--shmem-compilers OpenSHMEM` as the warning messages suggest does not seem to be working as expected.

**Comment by zbeekman** [comment]
I thought that going two levels below home was fixing it for me. It’s
possible my environment changed in some other way. Or perhaps the name of
the directory matters? I’m not sure, but I remember being quite convinced
and surprised that it would go away when the top lev l project dir was
something like ~/foo/bar but appeared when it was ~/foo.

I could be mistaken.

**Comment by khsa1** [comment]
I cannot reproduce this behavior. Since TAU Commander is guessing which version of SHMEM is being used, it's possible that it is being randomly printed and does not depend on the location of the directory.

Could you try again with the latest commit on unstable. It should make the way TAU Commander guesses the SHMEM compiler family more reliable.

**Comment by zbeekman** [comment]
Great, I’ll take a look when I return from travel next week. Thanks for
looking at this Sam.

**Comment by zbeekman** [comment]
I'm closing this as it is a duplicate of #232. The problem arises when using the `mpi/sgimpt/2.12-11218` module. The default `mpi/sgimpt/2.15` module does not trigger this issue.
