### ISSUE TITLE
nightly with date and update mechanism

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#267]
It would be nice if `--tau nightly` created a directory named `system/tau/tau-nightly-yyyy-mm-dd` and `system/src/tau/tau-nightly-yyyy-mm-dd.tgz` instead of just "tau-nightly" to help with debugging efforts and idiot proofing.

Also, some flag to `tau target edit` to tell TAU Commander to grab the latest TAU nightly. This may need to be a measurement attribute rather than a target attribute, but I'm not sure if that makes sense, or if there's a better approach.

**Comment by khsa1** [comment]
This feature is working as of aaf972cd4bdeb7b8a1eb9bf8d18154956c45461f.

`--tau nightly` creates a directory based on the date it was downloaded. That directory will be used unless `--update-date T` is passed to selected measurement.
