### ISSUE TITLE
Query selected experiment without parsing dashboard

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#275]
For scripting purposes it would be nice to have a `tau selected` command or `tau experiment current` to print the currently selected experiment for scripting purposes. Alternatively a flag added to `experiment list` could list just the selected experiment, or list the selected experiment first in the short output format.

**Comment by zbeekman** [comment]
If you parse the dash here is a one-liner to fetch the currently selected experiment:

```
tau dash | sed -n 'x; $p' | cut -d ' ' -f 3
```

**Comment by khsa1** [comment]
Added in b01c75266fb785105f50b332a065dcdcef2dffd8.
