### ISSUE TITLE
`tau` command runtime increases with number of experiments/trials

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#277]
First of all, commands like `tau dash` can start to take quite a long time:

```bash
$ time tau dash
...
real	1m51.385s
user	1m37.624s
sys	0m13.476s
# In the home directory file system on Onyx
$ pwd
/p/home/...
```

And then, much more alarmingly compilation times end up increasing quite a bit:

```bash
$ time ifort src/Testing/Solvers/mod_parse.f90

real	0m0.534s
user	0m0.124s
sys	0m0.236s
$ time tau ifort src/Testing/Solvers/mod_parse.f90

real	0m18.259s
user	0m14.024s
sys	0m3.480s
```

This is a ~34190% increase in compilation time when underlying TAU is not even being invoked!!!!! A 34X slow-down in compilation.

**Comment by zbeekman** [comment]
Reducing the number of trials by ~ 30-40% yields a more responsive tau commander:

```
$ time tau dash
...
real	1m5.863s
user	0m59.832s
sys	0m5.760s
```

**Comment by jlinford** [comment]
Try disabling transactions on the database.  Replace method body with pass
statement.  It's done in a stupid way : copies whole database. Just a
placeholder really

**Comment by nchaimov** [comment]
@zbeekman Can you try with 3015881f0b9c4f9b0a3eb0e85315c441d7120821 and see if it resolves the issue. It turns out caching is completely optional (and not enabled by default) in TinyDB, so every search would re-read and re-parse the entire database.

**Comment by zbeekman** [comment]
after https://github.com/ParaToolsInc/taucmdr/commit/3015881f0b9c4f9b0a3eb0e85315c441d7120821 (same number of trials/experiments as [last comment](https://github.com/ParaToolsInc/taucmdr/issues/277#issuecomment-387163732): 

```bash
$ time tau dash
...
real	0m1.257s
user	0m0.552s
sys	0m0.256s
```

🎉 

https://github.com/ParaToolsInc/taucmdr/commit/3015881f0b9c4f9b0a3eb0e85315c441d7120821 appears to completely fix this.

**Comment by nchaimov** [comment]
@zbeekman You should update to 234b37dcaed734b26f50c25d03635f6cce911285, though. The previous commit was caching both reads and writes which could break the transaction support
