### ISSUE TITLE
`tau trial edit --description` changes that trial FOR EVERY EXPERIMENT

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#281]
steps to reproduce:

1. create multiple experiments
2. create multiple trials in at least two experiments, each with a unique --description passed to `tau trial create`
3. `tau trial edit 0 --description "new desc"`

Now go checkout your other experiment(s). The old description for trial 0 will be replaced by "new desc"

**Comment by khsa1** [comment]
Fixed in 33c0305.
