### ISSUE TITLE
respect $TERM

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#291]
Don't emit ansii escape sequences on dumb terms or when redirecting output.

**Comment by zbeekman** [comment]
Hi Sam, thanks for working on this! I'll test and see if I can add some additional logic to ensure this works as expected.

**Comment by khsa1** [comment]
It's still a work in progress. My last commit removed some of the escape sequences but not all of them.

**Comment by zbeekman** [comment]
There’s a way to globally control the color module we’re using. Shouldn’t that take care of 99% of it?

**Comment by khsa1** [comment]
That's what I was hoping. I tried disabling coloring in `color_text` function of `util.py`, but that didn't remove all the ascii characters. Maybe there are non-color ascii characters?

**Comment by khsa1** [comment]
Nevermind, color also being added by the texttable module. This is working after 4172c6d4efa9431c264341e5393cd047ea5b8fff.
