### ISSUE TITLE
4. Pass tags to taucmdr

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#294]
(From Sameer's email)

We need a way to pass tags to TAU Commander. Many installations at the labs already have tags that they use with other modules. For instance, at LANL, if I use:
```
module load intel
module load openmpi
module load tau
```
it loads `TAU/2.27.1` with a tag `-intel_18.0.2_openmpi_2.1.0`  (which is set in an LTAG environment variable). So, we launch `tau_exec` using:
```mpirun -np 4 tau_exec -T $TAU_LTAG,icpc,mpi,papi,pdt  ./a.out```

If we have multiple builds of `make install INSTALLDIR=prefix TAU=full` with some sort of a tag, we need to figure out how that would work. 
Also, while using a tau configuration in `tau dash`, we would need a way to specify a specific tag. I guess we can use the “force TAU to use this Makefile” option in `tau meas edit` … or so. But, perhaps it will be cleaner if we specify it in tau init —tag=<tag> option. Well, it may make sense to have
`tau init —makefile=<tau_makefile>` as well.

**Comment by khsa1** [comment]
(From Sameer's email)

What I meant was if the sysadmin has already installed multiple configurations of TAU with tags and uses TAU Commander installation with something like:
```make install INSTALLDIR=TC_prefix TAU=/path/to/tau-2.27.1``` and the user wants to pick something like `Makefile.tau-intel_18.0_openmpi_2.1-icpc-mpi-pdt` then, is there a way during `tau init` for specifying the use of `intel_18.0_openmpi_2.1` tag (instead of `intel_17.0_openmpi_2.1`) with a `-tag=<tag>` parameter to narrow the search?

**Comment by zbeekman** [comment]
# 4 in Sameer's email

**Comment by zbeekman** [comment]
Is this related to #295 ?

**Comment by khsa1** [comment]
Added in 67b022a4554bf8ef011ee7de707de0f4d0e984bb.
