### ISSUE TITLE
8. Recognizing mpirun variants

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#298]
I recall checking in `ccc_mprun` as a valid replacement for `srun`/`mpirun`. There are two others:
```
mpiexec_mpt
```
and 
```
mpirun_rsh
```
that should also be recognized. This is a simple fix. `grep -r ccc_mprun *` and add another line.

**Comment by zbeekman** [comment]
8. From Sameer's email

**Comment by zbeekman** [comment]
fixed in cbd9f902c238a815e7dd9fb24df2eb83549ffedf

I don't think additional tests make sense, unless we could try a build matrix with slurm and/or change the MPI implementation.
