### ISSUE TITLE
1. TR6 needs a tau configure option (upstream) to allow pre-built tr6

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#303]
TAU's configure script doesn't know that cmdr is downloading and building TR6 itself. There is currently no way to tell TAU's configure that the OMPT that we're pointing it to is TR6, not TR4. There is no obvious way to detect whether a given installation is TR6, not TR4, so an extra option is likely needed in TAU's configure script to allow for pointing at TR6 OMPT installs.

**Comment by zbeekman** [comment]
This corresponds to:

>1. We need a way to use -ompt=download-tr6 with TAU Commander. With this option, we need for a user to specify: 
export TAU_OMPT_SUPPORT_LEVEL=default/full
>
>and automatically set:
TAU_OMPT_RESOLVE_ADDRESS_EAGERLY=1
	while launching the binary with tau mpirun ./a.out
>
>There is also a bug in TAU (git head) that gives runtime overlaps with this option while using tau_exec -T ompt,tr6,pdt -ompt ./a.out that shows up with single threaded Lulesh 2.0 and SNAP benchmark runs.

From Sameer's email

**Comment by nchaimov** [comment]
Fixed in e805b26dfeaeedb0b743764c941b111d5d9e505f and in TAU repo. There is now an -ompt-tr6 flag to TAU's configure script. When --ompt=download-tr6 is specified in TAU Commander, it will pass that to TAU's configure script.
