### ISSUE TITLE
Baseline measurement warnings with MPI applications

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#307]
We either need to silence the warning when the baseline measurement is enabled with an MPI application, or address an underlying issue in how baseline and/or measurements in general are dealing with application attributes.

**Comment by nchaimov** [comment]
With a baseline measurement, it doesn’t matter what the application attributes are, right? Since all we’re doing is timing end-to-end application time, it doesn’t matter whether the application is MPI or not — we do the same thing either way.

**Comment by zbeekman** [comment]
Yes exactly. I just wanted to remind myself to look into the logic
why/when/how the warning is issued, and whether I should have a special
case to silence it for baseline or if there’s a better, more generic fix to
be made.

**Comment by zbeekman** [comment]
specific fix (baseline measurement with MPI, caf, OpenCL application) implemented in 14d345a21bbb7ebf2e278b5e5079bd6ba178037a
