### ISSUE TITLE
Comma-separated --metrics list results in wrong number of metrics

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#309]
If the user passes a comma-separated list to --metrics, TAU Commander interprets the comma-separated list as one metric with a name containing lots of commas. It then builds TAU with TAU_MAX_METRICS=1, but, since the TAU_METRICS environment variable expects a comma-separated list anyways, the correct metrics get set, resulting in a runtime failure because TAU_MAX_METRICS was exceeded.

TAU Commander should either 1) support either a space- or comma-separated metrics list or 2) give an error when the metrics list is set that it is in the wrong format, instead of appearing to work but then failing at runtime.

**Comment by khsa1** [comment]
90c2948fd413d9ee415bb43d3793eadcec4f2644 splits comma-separated metrics.
