### ISSUE TITLE
tau icc fails 

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#31]
initialized with:
tau init --host-compilers=Intel
customized measurements and applications
attempt to build with tau icc mm.c and fails hard:
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected TypeError exception was raised:
[TAU] 
[TAU] unhashable type: 'list'
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/tau", line 49, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cli/commands/**main**.py", line 131, in main
[TAU]     return cli.execute_command(shortcut, cmd_args)
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cli/**init**.py", line 277, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cli/commands/build.py", line 76, in main
[TAU]     return expr.managed_build(args.cmd, args.cmd_args)
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/model/experiment.py", line 280, in managed_build
[TAU]     tau = self.configure()
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/model/experiment.py", line 257, in configure
[TAU]     return self.configure_tau(prefix, dependencies)
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/model/experiment.py", line 227, in configure_tau
[TAU]     tau.install()
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cf/software/tau_installation.py", line 429, in install
[TAU]     return self._verify()
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cf/software/tau_installation.py", line 271, in _verify
[TAU]     makefile = self.get_makefile()
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cf/software/tau_installation.py", line 515, in get_makefile
[TAU]     config_tags = self.get_makefile_tags()
[TAU]   File "/home/users/dmackay/tcref/taucmdr/bin/../packages/tau/cf/software/tau_installation.py", line 470, in 
[TAU]     get_makefile_tags
[TAU]     tags.append(openmp_tags[self.measure_openmp])
[TAU] TypeError: unhashable type: 'list'
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/home/users/dmackay/.tau/debug_log' to support@paratools.com for assistance.
[debug_log_tauicc.txt](https://github.com/ParaToolsInc/taucmdr/files/143253/debug_log_tauicc.txt)

**Comment by jlinford** [comment]
Works as of b74c99022925f83a153a79e2df2f759a68322e77
