### ISSUE TITLE
TAU Cmdr doesn't like `BFDINCLUDE=-IDir1 -IDir2`

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#320]
This change was to support spack. We need to find a way to pass both include directories.

From Sameer's email:
>From the message, it sounds like TAU Commander doesn't like:
BFDINCLUDE=-IDir1 -IDir2
It expects:
BFDINCLUDE=-IDIR1
only and has some logic to check that DIR1 exists. When it sees two, the logic needs to be updated tocheck that both exist or to ignore this check and not mark it as a critical error reporting that Dir1<space>-IDir2 is not a directory. This check probably predates the change to TAU to support Spack's use of two directories to copy over extra ELF header files to  the extra/ directory.

**Comment by nchaimov** [comment]
Fixed in 3bd938b88d5951ecc2d4a88c3138a22c80b2cbb3.
