### ISSUE TITLE
Support OMPT 5.0 and native OMPT when supported compiler is used

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#326]
In 2.29 and nightly TAU, there is now support for using OMPT TR7/5.0 with the Intel 19 and later compilers. Intel 19 has this support built-in, so with it there is no longer any need to pre-load the LLVM OpenMP runtime. Instead, with Intel 19, TAU can be configured to use the built-in OMPT support by passing in `-ompt` to TAU's `configure` script, without `=download`,  `=download-tr6`, or a path.

**Comment by nchaimov** [comment]
It appears that this has already been partially done in commit a32c89017c6ce499c577a7866bc40810b7e550a9. 

We still need to support OMPT 5.0 using the LLVM OpenMP runtime, and add tags correctly for the different versions. TAU Commander currently supports TR4 (default) and TR6:

https://github.com/ParaToolsInc/taucmdr/blob/dc9e0c1a6dc8f8eab9057cc12b8b2b1dea05b00a/packages/taucmdr/cf/software/ompt_installation.py#L51-L55

and can add tags for those:

https://github.com/ParaToolsInc/taucmdr/blob/dc9e0c1a6dc8f8eab9057cc12b8b2b1dea05b00a/packages/taucmdr/cf/software/tau_installation.py#L855-L872

TAU now has support for OpenMP 5.0 OMPT as well:

https://github.com/UO-OACISS/tau2/blob/d73d6aa25d18c978d391614082f3a84af27f822f/configure#L7552-L7568

which downloads a different runtime (http://tau.uoregon.edu/LLVM-openmp-8.0.tar.gz) and uses a new tag, `v5`.

TAU Commander should:

- Support the LLVM OpenMP 5.0 runtime for OMPT for compilers that don't support native OMPT, by downloading the runtime at http://tau.uoregon.edu/LLVM-openmp-8.0.tar.gz and using the tags `ompt` and `v5` with it.
- Make the LLVM OpenMP 5.0 runtime the default option.
- Support TR4 and TR6 as options if requested.

**Comment by nchaimov** [comment]
Other places in TAU Commander that may need to change to change the arguments to `-ompt`:

https://github.com/ParaToolsInc/taucmdr/blob/33190f5268678979700793229602a5ec7638783e/packages/taucmdr/cli/arguments.py#L475-L476

https://github.com/ParaToolsInc/taucmdr/blob/33190f5268678979700793229602a5ec7638783e/packages/taucmdr/cf/software/installation.py#L214-L219

https://github.com/ParaToolsInc/taucmdr/blob/33190f5268678979700793229602a5ec7638783e/packages/taucmdr/model/target.py#L445-L454

**Comment by khsa1** [comment]
@nchaimov For TR6 we use manually download/build and then use the `-ompt-tr6` flag to point to the directory but I do not see a `-ompt-tr4` option for TR4 in the TAU configure file. Do we need to add this option to TAU or should it be handled differently by taucmdr?

**Comment by nchaimov** [comment]
@khsa1 We probably need to add one to TAU's configure script.

**Comment by nchaimov** [comment]
Implemented in #380.
