### ISSUE TITLE
tau initialize broken on master (6dbcf355)

### ISSUE THREAD

**Issue by qwofford** [ParaToolsInc/taucmdr#328]
```
[TAU] CRITICAL
[TAU] 
[TAU] BFDINCLUDE in '<my install path>/system/tau/./tau-2.28.2/x86_64/lib/Makefile.tau-0c17ee66' is not a directory

```

There's an extraneous "./" in there that breaks things.

**Comment by nchaimov** [comment]
You may want to use the unstable branch. I believe this is fixed there. There was a change in upstream TAU that altered the format of the BFDINCLUDE entry in TAU's Makefile.

**Comment by qwofford** [comment]
Yes, the unstable branch initializes ok. Thank you.

**Comment by nchaimov** [comment]
Glad that worked. We are planning a new stable release prior to SC19, at which point we will update master.
