### ISSUE TITLE
mic setup problems

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#33]
I build the code like this for mic:
`mpiicc -O2 -fopenmp -mmic mpimm.c -lrt -o 4miccla.out`
When I initialize tau (knc, openmp, mpi) and change build:
`tau mpiicc -O2 -fopenmp -mmic mpimm.c -lrt -o 4miccla.out`
then I get at tau configure fail.

See attached log.
-David
[mic_debug_log.txt](https://github.com/ParaToolsInc/taucmdr/files/145734/mic_debug_log.txt)

**Comment by jlinford** [comment]
KNC support probably won't happen since we have KNL now.
