### ISSUE TITLE
tau create target fails to detect PGI family compilers

### ISSUE THREAD

**Issue by mjf-89** [ParaToolsInc/taucmdr#330]
As explained in the title tau commander fails to detect PGI compilers.  

I think the issue may be solved simply changing the regex used from: 

PGI = HOST_COMPILERS.add('PGI', **family_regex=r'The Portland Group'**,
                         CC='pgcc', CXX=('pgCC', 'pgc++', 'pgcxx'), FC=('pgfortran', 'pgf90', 'pgf77'))

to:

PGI = HOST_COMPILERS.add('PGI', **family_regex=r'NVIDIA CORPORATION'**,
                         CC='pgcc', CXX=('pgCC', 'pgc++', 'pgcxx'), FC=('pgfortran', 'pgf90', 'pgf77'))

in https://github.com/ParaToolsInc/taucmdr/blob/master/packages/taucmdr/cf/compiler/host.py

**Comment by khsa1** [comment]
`NVIDIA  COPRORATION` added to regex for PGI in 5cf0ce0810be5497afa5bfb0854cd1191dddf97b.
