### ISSUE TITLE
Is full Anaconda really required?

### ISSUE THREAD

**Issue by brnorris03** [ParaToolsInc/taucmdr#340]
The build time and size with full conda are huge, and some facilities have pretty severe disk quotas. Would it be possible to consider reworking the install to use miniconda and then adding whatever few extra packages are needed?

**Comment by nchaimov** [comment]
Only the enterprise branch currently uses the full Anaconda; the other branches use miniconda. We are currently looking in to using a custom anaconda distribution with just the packages TAU Commander actually needs.

**Comment by brnorris03** [comment]
That is not my experience today. I did a clean clone of master, which installed Anaconda. Maybe it ran into some old config? Why and how would it do that? My environment was clean.

**Comment by nchaimov** [comment]
The master branch should definitely be installing Miniconda, not Anaconda. The Makefile downloads Miniconda specifically:

https://github.com/ParaToolsInc/taucmdr/blob/33190f5268678979700793229602a5ec7638783e/Makefile#L121-L123

I just tested this and it appears to be downloading it correctly:

```nchaimov@delphi /home/nchaimov/testing/taucmdr $ make install INSTALLDIR=/home/nchaimov/testing/taucmdr-inst
--2020-03-13 15:48:02--  https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.18.201.79, 104.18.200.79, 2606:4700::6812:c84f, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.18.201.79|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 48243240 (46M) [application/x-sh]
Saving to: ‘system/src/Miniconda2-latest-Linux-x86_64.sh’```

It should download it anew so long as there is not an existing download of the conda installer at `./system/src` and there is not a conda installation in the INSTALLDIR you specified (`$INSTALLDIR/conda`). If there's an existing conda installation, it will use that instead.

When you run make, does it print anything initially about what file it is downloading?

**Comment by brnorris03** [comment]
I will check more carefully what happens in the beginning — I can’t connect right now, but as soon as I’m able, and let you know!

**Comment by brnorris03** [comment]
So there was a conda in the path, but it was for Python3. I removed it from PATH, and now it’s installing miniconda. Unrelated (?) to that, it fails to build TAU, however, see attached log file.
[install_log.txt](https://github.com/ParaToolsInc/taucmdr/files/4331942/install_log.txt)

**Comment by nchaimov** [comment]
The error relating to tau_trace2json and trace2profile should not actually prevent TAU from working, although that should be corrected. It should also not try to use a Python 3 Anaconda from the environment until the port to Python 3 is completed.

I've added issue #342 to track the build error messages and #341 to track the conda Python version issue.
