### ISSUE TITLE
Support libdwarf

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#373]
When TAU is used with sampling or compiler instrumentation, BFD is used to resolve samples by converting program counter addresses to function names. However, BFD is fairly slow, and for applications with a large number of symbols, sample resolution can take a long time. To fix this issue, TAU also supports using the much faster libdwarf (https://www.prevanders.net/dwarf.html).

When using plain TAU, DWARF can be used by specifying `-dwarf=download`. In TAU Commander however, we manage libraries ourselves instead of having TAU do it, so we need to download and build libdwarf and then pass `-dwarf=/path/to/dwarf` when building TAU.

Implementing this will involve:

- [x] Adding a new source file under `packages/taucmdr/cf/software` which will build and install libdwarf.
- [x] Modifying `packages/taucmdr/cf/software/tau_installation.py` so that it will depend on libdwarf and pass `-dwarf=/path/to/dwarf` when building TAU (except for minimal configurations).

The base class code that handles software installations is in `packages/taucmdr/cf/software/installation.py`. Look at `packages/taucmdr/cf/software/libotf2_installation.py` for the simplest possible example of a software installation class and at `ompt_installation.py` for a slightly more complicated example. 

In `tau_installation.py`, look for existing mentions of `unwind` or `bfd` to see how they are handled.

**Comment by nchaimov** [comment]
Also: the version of libdwarf that we use in TAU is available at http://www.cs.uoregon.edu/research/paracomp/tau/tauprofile/dist/libdwarf-20181024.tar.gz

That will be needed for creating the installation class in TAU Commander.

To get started, you may want to try building libdwarf yourself on one of the NIC/PRL machines at UO and installing it somewhere in your home directory (by passing e.g. `--prefix=$HOME/libdwarf-install` to install into that directory) , and then try building TAU manually (outside TAU Commander) with TAU pointed at your installation of libdwarf (`-dwarf=$HOME/libdwarf-install`).

**Comment by zbeekman** [comment]
Implemented in #382
