### ISSUE TITLE
Support '-unwinder=backtrace' and disallow libunwind on ppc64le

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#389]
It turns out that libunwind has serious bugs on ppc64le which can lead to segfaults when unwinding. We should either discourage or exclude the use of libunwind on ppc64le, and instead use a different unwinder, which is specified by passing `-unwinder=backtrace` as a configuration option to TAU. This option is only usable on compilers which use the `libgcc_s` library, however, which includes GCC and Clang, but not PGI.

**Comment by khsa1** [comment]
Added in b639d3e88b7c6395a8d59eb52344a441bcdf03b4.

@nchaimov From what I can tell taucmdr does not handle `clang` at the moment. The only mention I see of `clang` when I grep for it in the code is `armclang`. Would it make sense to add it as a compiler in `cf/compiler/host.py`?

**Comment by khsa1** [comment]
I tested on cyclops. When I try configuring tau with `unwinder=backtrace` it fails. Here is my full configure command:

```
./configure -tag=6788deea -arch=ibm64linux -cc=gcc -c++=g++ -fortran=gfortran  
-bfd=/storage/users/skhuvis/workspace/taucmdr/system/binutils/074a8d66  
-unwind=backtrace -useropt=-O2#-g#-DTAU_MAX_THREADS=25#-DTAU_MAX_METRICS=1#-DTAU_MAX_COUNTERS=1
```

TAU compilation fails with:
```
g++ -m64                                    -m64                                    -DTAU_LIBRARY_SOURCE  -O2 -g -DTAU_MAX_THREADS=25 -DTAU_MAX_METRICS=1 -DTAU_MAX_COUNTERS=1 -I/storage/users/skhuvis/workspace/taucmdr/system/tau/tau-nightly-2020-09-20/include -I/storage/users/skhuvis/workspace/taucmdr/system/tau/tau-nightly-2020-09-20/include/Profile -DPROFILING_ON                        -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS                     -DTAU_LINUX_TIMERS                                 -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -Ibacktrace/include    -DTAU_TRACK_LD_LOADER                   -fPIC            -c TauDisable.cpp
TauSampling_libunwind.cpp:11:23: fatal error: libunwind.h: No such file or directory
 #include <libunwind.h>
```

**Comment by nchaimov** [comment]
This was added in #391 and #402
