### ISSUE TITLE
Update TAU dependencies

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#394]
At least binutils is outdated: we currently pull binutils 2.27 but should get 2.36 instead. We should check the current versions of dependencies used by TAU's configure script and ensure that TAU Commander uses the same versions.

**Comment by zbeekman** [comment]
Versions currently used by the TAU configure script:

- [ ] binutils 2.36
- [ ] libunwind 1.3.1 / 1.3-rc1
- [ ] LLVM-openmp
- [ ] otf2
- [ ] papi
- [ ] scorep
- [ ] libdwarf
- [ ] libelf

**Comment by zbeekman** [comment]
Resolved in https://github.com/ParaToolsInc/taucmdr/commit/26bff988d5d1f64e46e37b150bf9302ea7cc657a
