### ISSUE TITLE
tua mpicc using mpich and gcc 

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#40]
mpicc file.c build a.out
tau mpicc file.c fails
Attached log file and .json file.
project.json file moved to projectjson.txt in order to satisfy github upload.
[debug_log.txt](https://github.com/ParaToolsInc/taucmdr/files/164176/debug_log.txt)

[projectjson.txt](https://github.com/ParaToolsInc/taucmdr/files/164178/projectjson.txt)

**Comment by zbeekman** [comment]
If we setup some regression tests, this is a configuration that we could test on travis-ci.

**Comment by drmackay** [comment]
Changes merged in by John on 8 March resolved this.  I verified it on two different ubuntu vms.
