### ISSUE TITLE
Allow specifying 'None' for compiler families

### ISSUE THREAD

**Issue by nchaimov** [ParaToolsInc/taucmdr#400]
Many command line arguments in TAU Commander can accept 'None' as a parameter to specify that none applies. However, this does not appear to work for compiler families, even when, as in the case of MPI compilers, the attributes for the compilers are optional.

- [ ] Support explicitly unsetting the compiler family variables in Targets
- [ ] Support explicitly unsetting the individual compiler attributes in Targets
- [ ] Ensure that this works for all relevant commands, including `create`, `edit`, and `copy`
- [ ] Add tests for these. Tests should verify that manual unsetting overrides any automatically-detected compilers.
- [ ] Review the Model classes to check whether there are other attributes that should be able to be manually unset, but that currently can't be.

**Comment by khsa1** [comment]
MPI family and individual compilers can be set to None in 8ac1f196616b3e06e0748df10d92d8fce5b6bc47.

**Comment by khsa1** [comment]
I've pushed fixes for MPI and CUDA compilers to be set to None and added appropriate unittests. The pull request is #406.

**Comment by nchaimov** [comment]
This was fixed in #406, which has been merged into unstable.
