### ISSUE TITLE
Investigate/fix sphinx documentation errors/warnings

### ISSUE THREAD

**Issue by zbeekman** [ParaToolsInc/taucmdr#45]
See, for example: https://travis-ci.org/ParaToolsInc/taucmdr/jobs/124867593#L482-L664

@srinathv John told me you set up most of the awesome sphinx documentation, any insight, or other help would certainly be welcome.

**Comment by jlinford** [comment]
This isn't a priority, and since @srinathv isn't with us anymore I'm marking this as wontfix.
