### ISSUE TITLE
inline gcc 4 vs. gcc 5 mm example?

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#46]
I am running the mm example codes on two different systems - one using gcc 4.8.5 the other using gcc 5.2.1.  The mm example fails to build on the system with gcc 5.2.1   This is not due to tau commander, but the underlying system (if I alter the Makefile and change `CC = mpicc` and `CC = gcc` (remove `tau gcc` and `tau mpicc`) the build fails as well.  When I edit `matmult.c` and delete the keyword `__inline`  (`__inline multiply( . . . )` , then mm example builds successfully.  This is true both with and without tau commander.  We should make the examples work regardless of gcc version.  CORRECTION is to change `__inline` to `static __inline` this works for both gcc 5.2.1 and gcc 4.8.5, where else should this be tested?

**Comment by zbeekman** [comment]
So this is an issue with TAU itself, not taucmdr, yes?
