### ISSUE TITLE
Failure with tau show after collecting trace data.

### ISSUE THREAD

**Issue by drmackay** [ParaToolsInc/taucmdr#51]
```
 CRITICAL
[TAU] 
[TAU] An unexpected InternalError exception was raised:
[TAU] 
[TAU] Nonzero return code from tau2slog2 tau.trc tau.edf -o tau.slog2
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/home/drmackay/taucmdr/bin/tau", line 48, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/home/drmackay/taucmdr/bin/../packages/tau/cli/commands/__main__.py", line 131, in main
[TAU]     return cli.execute_command(shortcut, cmd_args)
[TAU]   File "/home/drmackay/taucmdr/bin/../packages/tau/cli/__init__.py", line 277, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/home/drmackay/taucmdr/bin/../packages/tau/cli/commands/trial/show.py", line 75, in main
[TAU]     return expr.show(trial_numbers=numbers, profile_tool=profile_tool, trace_tool=trace_tool)
[TAU]   File "/home/drmackay/taucmdr/bin/../packages/tau/model/experiment.py", line 394, in show
[TAU]     tau.show_trace(prefix, trace_tool)
[TAU]   File "/home/drmackay/taucmdr/bin/../packages/tau/cf/software/tau_installation.py", line 802, in 
[TAU]     show_trace
[TAU]     raise InternalError("Nonzero return code from %s" % ' '.join(cmd))
[TAU] InternalError
[TAU] 
[TAU] This is a bug in TAU Commander.
[TAU] Please send '/home/drmackay/.tau/debug_log' to <support@paratools.com> for assistance.
```

[debug_log.txt](https://github.com/ParaToolsInc/taucmdr/files/283098/debug_log.txt)

**Comment by jlinford** [comment]
Hi David,

Can you please try with the unstable branch and see if this still breaks?
Thanks,

~John C.


On Wed, May 25, 2016 at 5:24 PM, drmackay <notifications@github.com> wrote:

> CRITICAL
> [TAU]
> [TAU] An unexpected InternalError exception was raised:
> [TAU]
> [TAU] Nonzero return code from tau2slog2 tau.trc tau.edf -o tau.slog2
> [TAU]
> [TAU] Traceback (most recent call last):
> [TAU] File "/home/drmackay/taucmdr/bin/tau", line 48, in
> [TAU] sys.exit(cli_main_cmd.main(sys.argv[1:]))
> [TAU] File "/home/drmackay/taucmdr/bin/../packages/tau/cli/commands/*main*.py",
> line 131, in main
> [TAU] return cli.execute_command(shortcut, cmd_args)
> [TAU] File "/home/drmackay/taucmdr/bin/../packages/tau/cli/*init*.py",
> line 277, in execute_command
> [TAU] return main(cmd_args or [])
> [TAU] File
> "/home/drmackay/taucmdr/bin/../packages/tau/cli/commands/trial/show.py",
> line 75, in main
> [TAU] return expr.show(trial_numbers=numbers, profile_tool=profile_tool,
> trace_tool=trace_tool)
> [TAU] File
> "/home/drmackay/taucmdr/bin/../packages/tau/model/experiment.py", line 394,
> in show
> [TAU] tau.show_trace(prefix, trace_tool)
> [TAU] File
> "/home/drmackay/taucmdr/bin/../packages/tau/cf/software/tau_installation.py",
> line 802, in
> [TAU] show_trace
> [TAU] raise InternalError("Nonzero return code from %s" % ' '.join(cmd))
> [TAU] InternalError
> [TAU]
> [TAU] This is a bug in TAU Commander.
> [TAU] Please send '/home/drmackay/.tau/debug_log' to support@paratools.com
> for assistance.
>
> debug_log.txt
> <https://github.com/ParaToolsInc/taucmdr/files/283098/debug_log.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ParaToolsInc/taucmdr/issues/51>
>



-- 
http://www.google.com/profiles/john.christian.linford
