### ISSUE TITLE
papi metrics stalling build/check for tau commander on CNL

### ISSUE THREAD

**Issue by srinathv** [ParaToolsInc/taucmdr#57]
This is on shepard.navo.hpc.mil.
I shifted from trying to use "tau ftn" in the configure script for FUN3D to just trying to use it with matmult.f90:

Here is my history:
 1299  tau init
 1300  tau app bld-limInst --use-mpi
 1301  tau app edit bld-limInst --use-mpi
 1302  tau meas edit instrument -h
 1303  tau meas edit instrument --heap-usage=T --mpi --keep-inst-files
 1304  module list
 1305  tau meas edit instrument --metrics TIME PAPI_FP_INS PAPI_L1_DCM PAPI_L2_DCM
 1306  ls
 1307  vim thisconfig.sh
 1308  ./thisconfig.sh
 1309  ls
 1310  tau ftn matmult.f90 -o matmult
 1311  ls
 1312  tau dash
 1313  tau select instrument

[debug_log.txt](https://github.com/ParaToolsInc/taucmdr/files/335937/debug_log.txt)

**Comment by jlinford** [comment]
This works as of 15211d4c2ce72dd8faa805ba0de1d0895a843007.
