### ISSUE TITLE
Progress bar on KNL

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#59]
Progress bar while downloading packages jumps immediately to 100%.

**Comment by jlinford** [comment]
Pretty sure that's because the KNL is hosted in the same rack as the storage server.  Can you duplicate this anywhere else?  If I fudge the download link to be slower then I see incremental progress.

**Comment by khsa1** [comment]
No, I was seeing a gap in time between the progress bar going to 100% and the tgz file being extracted but I think you are right and it was just downloading very quickly.
