### ISSUE TITLE
Stop using a select file

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#60]
After a tau select file is selected, there is no option to stop using that select file. There should be the option to do 
tau measurement edit meas1 --select-file=none
so that no select file is used.

**Comment by zbeekman** [comment]
I think instead of `tau measurement edit meas1 --select-file=none` you meant `tau application edit --select-file=none`

**Comment by khsa1** [comment]
Fixed in 6f0e771dab0d.
