### ISSUE TITLE
tau init does not select a project configuration

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#76]
$ tau init
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] The project has been initialized but no project configuration is selected.
[TAU] 
[TAU] Hints:
[TAU]   * Use `tau project create` to create a new project configuration.
[TAU]   * Use `tau select <project_name>` to select a project configuration.
[TAU]   * Use `tau project list` to see available project configurations.
[TAU] 
[TAU] TAU cannot proceed with the given inputs.
[TAU] Please check the selected configuration for errors or contact <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by jlinford** [comment]
Fixed on 77fff882912cdd541cd298f7b4131f8ed13fee39.
