### ISSUE TITLE
tau init --from-tau-makefile causes critical error

### ISSUE THREAD

**Issue by khsa1** [ParaToolsInc/taucmdr#85]
surface86{shende1}64: tau init --from-tau-makefile /usr/global/tools/tau/training//tau_latest/x86_64/lib/Makefile.tau-icpc-mpi-pdt
[TAU] Created a new project named 'matmult'.
[TAU] Selected project 'matmult'. No experiment.
[TAU] Parsing TAU Makefile '/usr/global/tools/tau/training//tau_latest/x86_64/lib/Makefile.tau-icpc-mpi-pdt' to populate command line 
[TAU]     arguments:
[TAU]   --host-arch='x86_64'
[TAU]   --host-os='Linux'
[TAU]   --tau='/usr/global/tools/tau/training/tau_latest'
[TAU]   --papi='None'
[TAU]   --pdt='/usr/global/tools/tau/training/pdtoolkit-3.22.1'
[TAU]   --scorep='None'
[TAU] Probing Intel MPI C++ compiler '/usr/local/bin/mpiicpc' to discover wrapped compiler
[TAU]   '/usr/local/bin/mpiicpc' wraps '/usr/local/bin/icpc'
[TAU]   --mpi-cxx='/usr/local/bin/mpiicpc'
[TAU]   --cxx='/usr/local/bin/icpc'
[TAU] Probing Intel MPI C compiler '/usr/local/bin/mpiicc' to discover wrapped compiler
[TAU]   '/usr/local/bin/mpiicc' wraps '/usr/local/bin/icc'
[TAU]   --mpi-cc='/usr/local/bin/mpiicc'
[TAU]   --cc='/usr/local/bin/icc'
[TAU]   --libunwind='/usr/global/tools/tau/training/tau-2.25.2/x86_64/libunwind-1.1-mpiicc'
[TAU]   --fc='/usr/local/bin/ifort'
[TAU]   --fc='/usr/local/bin/ifort'
[TAU] Probing Intel MPI Fortran compiler '/usr/local/bin/mpiifort' to discover wrapped compiler
[TAU]   '/usr/local/bin/mpiifort' wraps '/usr/local/bin/ifort'
[TAU]   --mpi-fc='/usr/local/bin/mpiifort'
[TAU]   --fc='/usr/local/bin/ifort'
[TAU]   --binutils='/usr/global/tools/tau/training/tau-2.25.2/x86_64/binutils-2.23.2'
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
[TAU] 
[TAU] CRITICAL
[TAU] 
[TAU] An unexpected KeyError exception was raised:
[TAU] 
[TAU] <tau.cf.compiler.CompilerRole object at 0x2aaaaf7a7e50>
[TAU] 
[TAU] Traceback (most recent call last):
[TAU]   File "/usr/global/tools/tau/training//taucmdr/bin/tau", line 48, in <module>
[TAU]     sys.exit(cli_main_cmd.main(sys.argv[1:]))
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cli/commands/__main__.py", line 160, in main
[TAU]     return cli.execute_command([cmd], cmd_args)
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cli/__init__.py", line 277, in execute_command
[TAU]     return main(cmd_args or [])
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cli/commands/initialize.py", line 214, in main
[TAU]     self._populate_project(argv, args)
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cli/commands/initialize.py", line 167, in _populate_project
[TAU]     _safe_execute(target_create_cmd, target_argv)
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cli/commands/initialize.py", line 138, in _safe_execute
[TAU]     retval = cmd.main(argv)
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cli/commands/target/create.py", line 219, in main
[TAU]     compilers = self.parse_compiler_flags(args)
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cli/commands/target/create.py", line 97, in parse_compiler_flags
[TAU]     compilers[role] = InstalledCompiler.probe(absolute_path, role=role)
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cf/compiler/installed.py", line 279, in probe
[TAU]     info_list = CompilerInfo.find(command, family, role)
[TAU]   File "/usr/global/tools/tau/training/taucmdr/bin/../packages/tau/cf/compiler/__init__.py", line 138, in find
[TAU]     return [info for info in family.members[role] if info.command == command]
[TAU] KeyError: <tau.cf.compiler.CompilerRole object at 0x2aaaaf7a7e50>
[TAU] This is a bug in TAU Commander.
[TAU] Please use --log to enable debug logging and send '/g/g24/shende1/.tau/debug_log' to <support@paratools.com> for assistance.
[TAU] 
[TAU] XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by jlinford** [comment]
Resolved in be1d3ac678701d9d9ea69ee3e8c435689a1ed7ea.
