### ISSUE TITLE
Show build output when build fails.

### ISSUE THREAD

**Issue by jlinford** [ParaToolsInc/taucmdr#88]

**Comment by khsa1** [comment]
Added in 9a22285a832c5a7b31a.

**Comment by jlinford** [comment]
I'm getting a UnicodeDecodeError on east03, possibly because of this fix.  See attached.  Use `python setup.py test` on east03 to reproduce.

[debug_log.gz](https://github.com/ParaToolsInc/taucmdr/files/1331165/debug_log.gz)

**Comment by jlinford** [comment]
Reverting 9a22285 does seem to fix it.

**Comment by jlinford** [comment]
Restored in 30143a7b52acac95577c2842562c9835745d8255.
