### ISSUE TITLE
tail +2 fails on ubuntu

### ISSUE THREAD

**Issue by wohlbier** [ParaToolsInc/taucmdr#91]
Line 142 in Makefile:
	@tail +2 "$(TAU)" > "$(BUILDDIR)/tau.tail"
fails on Ubuntu linux. Replacing with
	@tail -n +2 "$(TAU)" > "$(BUILDDIR)/tau.tail"
works.

Relevant so thread:
http://stackoverflow.com/questions/6185543/is-tail-2-supported-by-linux

**Comment by jlinford** [comment]
Fixed in cca83546a1cfa2d44fd50026c0d5923f5c97cd22
